# Configuration section for Database.
DATABASE:
  TYPE: SQLITE
  # Configuration section for Sqlite.
  SQLITE:
    # The text or value for File. Available options: Any valid string text
    FILE: data/data.db
  # Configuration section for Mysql.
  MYSQL:
    # The text or value for Host. Available options: Any valid string text
    HOST: localhost
    # The numerical value for Port. Available options: Any valid integer
    PORT: 3306
    # The text or value for Database. Available options: Any valid string text
    DATABASE: ultimatedonutsmp
    # The text or value for Username. Available options: Any valid string text
    USERNAME: root
    # The text or value for Password. Available options: Any valid string text
    PASSWORD: ''
    # Determines whether Create Database is enabled or disabled. Available options: true, false
    CREATE-DATABASE: true
    # The text or value for Parameters. Available options: Any valid string text
    PARAMETERS: useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
  # Configuration section for Mongodb.
  MONGODB:
    # The text or value for Uri. Available options: Any valid string text
    URI: mongodb://localhost:27017
    # The text or value for Database. Available options: Any valid string text
    DATABASE: ultimatedonutsmp
    # The text or value for Cache File. Available options: Any valid string text
    CACHE-FILE: data/mongodb-cache.db
    # Determines whether Sync On Autosave is enabled or disabled. Available options: true, false
    SYNC-ON-AUTOSAVE: true
